# -*- coding: utf-8 -*-
"""TCC540-a2026s2n11grupo1-UNIVESP-2026_OQUE_É_INTELIGENCIA_ARTIFICIAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BkJCB0uO75wFMCfvZ_Rrvxm8xJEYEvwn

# none do grupo TCC540-a2026s2n11grupo1-UNIVESP-2026

## Algoritmo de IA: Uma Demonstração e Comparação com a Inteligência Biológica

Neste notebook, exploraremos um algoritmo de Inteligência Artificial simples e demonstraremos como ele 'aprende' a classificar dados. Em seguida, faremos uma breve comparação entre a forma como a IA opera e a complexidade da inteligência humana ou de organismos biológicos, destacando o vasto potencial da IA.

### 1. Preparação e Carregamento de Dados

Vamos usar o famoso dataset Iris, um conjunto de dados clássico em machine learning para problemas de classificação. Ele contém medidas de pétalas e sépalas de três espécies de flores Iris.
"""

import pandas as pd
from sklearn.datasets import load_iris

# Carregar o dataset Iris
iris = load_iris()

# Converter para um DataFrame pandas para facilitar a manipulação
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target

# Mapear os alvos numéricos para nomes de espécies
df['species_name'] = df['species'].map({i: name for i, name in enumerate(iris.target_names)})

print("Primeiras 5 linhas do dataset Iris:")
display(df.head())

"""### 2. Demonstração de um Algoritmo de IA: Árvore de Decisão

Usaremos um algoritmo de Árvore de Decisão para classificar as espécies de Iris com base nas suas características. Uma Árvore de Decisão é um modelo intuitivo que toma decisões sequenciais, como um 'fluxograma', para chegar a uma classificação.
"""

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

# Separar características (X) e o alvo (y)
X = df[iris.feature_names]
y = df['species']

# Dividir os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Inicializar e treinar o modelo de Árvore de Decisão
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred = model.predict(X_test)

# Avaliar a performance do modelo
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=iris.target_names)

print(f"Acurácia do Modelo: {accuracy:.2f}")
print("\nRelatório de Classificação:\n", report)

"""### 3. Como a IA 'Aprende' (e a Comparação com a Inteligência Biológica)

Neste exemplo, a Árvore de Decisão 'aprendeu' as regras para classificar as flores de Iris analisando os padrões nos dados de treino. Ela identificou as características (como 'petal length') que melhor separam as diferentes espécies. Se a 'petal length' for menor que X, é a espécie A; caso contrário, se a 'petal width' for menor que Y, é a espécie B, e assim por diante.

**Inteligência Artificial (Modelo de Árvore de Decisão):**
*   **Aprendizado baseado em dados:** A IA encontra padrões estatísticos e relações nos dados fornecidos.
*   **Lógica explícita (mas complexa):** Para a Árvore de Decisão, as 'regras' são formadas por uma série de condições if/then.
*   **Foco em tarefas específicas:** É extremamente eficiente para a tarefa para a qual foi treinada (neste caso, classificar Iris).
*   **Falta de intuição/contexto:** Não entende o 'porquê' por trás das regras ou o contexto do mundo real das flores Iris. Não tem consciência ou sentimentos.

**Inteligência Humana/Biológica:**
*   **Aprendizado holístico e contextual:** Os humanos aprendem não apenas com dados, mas também com experiências, interações sociais, intuição, emoções e um vasto conhecimento de mundo.
*   **Raciocínio abstrato e criatividade:** Capacidade de generalizar, inovar, criar novas ideias e resolver problemas não vistos anteriormente.
*   **Consciência e autoconsciência:** Entendimento de si mesmo e do ambiente.
*   **Adaptabilidade:** Adapta-se rapidamente a novas situações e domínios de forma flexível.

A IA é poderosa em sua capacidade de processar grandes volumes de dados e encontrar padrões que seriam impossíveis para um humano identificar. No entanto, ela ainda carece da flexibilidade, da profundidade de compreensão e da consciência que definem a inteligência biológica.

### 4. O Potencial da Inteligência Artificial

Apesar das diferenças, o potencial da IA é imenso e transformador. Mesmo um algoritmo simples como a Árvore de Decisão pode ser a base para sistemas muito mais complexos. A IA está revolucionando diversas áreas:

*   **Saúde:** Diagnóstico de doenças, descoberta de medicamentos, medicina personalizada.
*   **Transporte:** Veículos autônomos, otimização de rotas.
*   **Finanças:** Detecção de fraudes, previsão de mercado, gestão de investimentos.
*   **Educação:** Tutores inteligentes, personalização do aprendizado.
*   **Ciência:** Descoberta de materiais, modelagem climática, exploração espacial.
*   **Automação:** Robótica, automação de processos industriais e de escritório.

À medida que os algoritmos se tornam mais sofisticados (como redes neurais profundas), e a capacidade de processamento de dados aumenta, a IA se aproxima de realizar tarefas que antes eram consideradas exclusivas da inteligência humana, como compreensão de linguagem natural, visão computacional e até mesmo geração de conteúdo criativo. O futuro da IA promete avanços ainda mais surpreendentes, complementando e estendendo as capacidades humanas.
"""
